[package]
name = "why-parser"
version = "0.1.0"
authors = ["Jorge Perez Burgos <vaijira@gmail.com>"]
edition = "2021"

[dependencies]
pest = "2.7"
pest_derive = "2.7"
why-data =  { path = "../why-data" }
