[package]
name = "why-data"
version = "0.1.0"
authors = ["Jorge Perez Burgos <vaijira@gmail.com>"]
edition = "2021"

[dependencies]
futures-signals = "0.3"
petgraph = "0.6"

[dependencies.web-sys]
version = "0.3"
features = [
    "SvgPathElement",
]

